export const theme = {
  colors: {
    background: '#F7F4F2',
    surface: '#FFFFFF',
    primary: '#7B4F9E',
    primaryLight: '#EDE4F5',
    success: '#2E7D32',
    successLight: '#F0FDF4',
    successBorder: '#86EFAC',
    warning: '#E65100',
    warningLight: '#FFF8F0',
    danger: '#C62828',
    dangerLight: '#FFEBEE',
    textPrimary: '#1A1A2E',
    textSecondary: '#6B7280',
    textLight: '#9CA3AF',
    border: '#E5E7EB',
    tabBar: '#FFFFFF',
    tabBarBorder: '#F3F4F6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
